name: CI Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  strategy:
    matrix:
      os: [ubuntu-latest, windows-latest]

  build:
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.4
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      - name: Setup
      run: |
        python3 setup.py
      - name: Test with pytest
      run: |
        .venv/Scripts/python.exe -m pytest
        
