name: Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read
    
jobs:
  build-test-deploy:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            pretty_name: Ubuntu Latest
            name: Ubuntu_Latest
            python_path: .venv/bin/python
            SCCG_deploy_path: ./deploy/dist/SCCG
          - os: windows-latest
            pretty_name: Windows Latest
            name: Windows_Latest
            python_path: .venv/Scripts/python.exe
            SCCG_deploy_path: ./deploy/dist/SCCG.exe
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.4"
      
      - name: Setup Project
        run: python3 setup.py
        
      - name: Pytest
        run: ${{ matrix.python_path }} -m pytest
        
      - name: Deploy
        run: ${{ matrix.python_path }} ./build.py
        
      - name: Upload Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release upload v0.0.1 ${{ matrix.SCCG_deploy_path }} --clobber

      - name: Badge
        if: always()
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: ${{ matrix.name }}
          LABEL: ${{ matrix.pretty_name }}
          STATUS: ${{ success() }}
          COLOR: Yellow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
