name: Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: write
    
jobs:
  build-test-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python_path: [.venv/bin/python, .venv/Scripts/python.exe]
        exclude:
          - os: ubuntu-latest
            python_path: .venv/Scripts/python.exe
          - os: windows-latest
            python_path: .venv/bin/python
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.4"
      
      - name: Setup Project
        run: python3 setup.py
        
      - name: Pytest
        run: ${{ matrix.python_path }} -m pytest
        
      - name: Upload Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release upload v0.0.1 ./deploy/dist/SCCG.exe --clobber
